sprinklr.settings:
  type: config_object
  label: 'Sprinklr settings'
  mapping:
    sprinklr_enabled:
      type: boolean
      label: 'Config to enable/disable sprinklr chatbot'
    allowed_urls:
      type: string
      label: 'List of URLs for sprinklr chatbot integration'
    urls_negate:
      type: integer
      label: 'Config to negate the sprinklr allowed urls condition'
    allowed_content_types:
      type: sequence
      label: 'List of content types for sprinklr integration'
      sequence:
        type: string
        label: 'Content type'
    app_id:
      type: text
      label: 'App id required to connect with sprinklr'
